### ISSUE TITLE
Create login page for Auth

### ISSUE THREAD

**Issue by Focuscode77** [Focuscode77/Best-Reads#6]
- [ ] ~~Should have login front end page.~~ 
https://github.com/Focuscode77/Best-Reads/pull/14
- [ ] ~~Create html file.~~
https://github.com/Focuscode77/Best-Reads/pull/14
- [x] Create path using MVC.

- [x] Have Auth Tested and working.

**Comment by AmjadShaaban** [comment]
login is not secure on front-end because it exposes the Service Account credentials.
we should be using passport and server side authentication.
